---
title: "2_28-3_13_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Set up libraries

```{r echo=FALSE}
library(ggplot2)
library(sys)
```

## Load CPC data

```{r}
# Before running this, add a .Renviron file to the project directory and add the line data_filename="<path to the .csv containing the data>"
airdata=read.csv(Sys.getenv("data_filename"),header=T,na.strings="?")
airdata <- na.omit(airdata[airdata$err_num==0,])
airdata$datetime <- as.POSIXct(airdata$timestamp, tz = "America/New_York", format = "%Y-%m-%dT%H:%M:%S", origin="1970-01-01")
purifier_start_time <- as.POSIXct(Sys.getenv("purifier_start_time"), tz = "America/New_York", format = "%Y-%m-%dT%H:%M:%S")

```

## Calculating indoor/outdoor particle ratio
```{r echo=FALSE}
indoor_data <- data.frame("concent" = double(), "sd"=double(), "datetime"=double())
outdoor_data <- data.frame("concent" = double(), "sd"=double(), "datetime"=double())

# Filter air data into indoor and outdoor rows
indoor_vals <- airdata[airdata$valve=="a",]
outdoor_vals <- airdata[airdata$valve=="b",]

# Get average + SD of each 5-min period for indoor values
start_idx <- 1
for (i in 2:length(indoor_vals$concent)-1) {
  time_diff <- unclass(indoor_vals$datetime[[i+1]]-indoor_vals$datetime[[i]])
  if (time_diff > 3) {
    section = indoor_vals[start_idx:i,]
    indoor_data[nrow(indoor_data)+1,] = c(mean(section$concent), sd(section$concent), indoor_vals$datetime[[i]])
    start_idx = i+1
  }
}
section = indoor_vals[start_idx:i,]
indoor_data[nrow(indoor_data)+1,] = c(mean(section$concent), sd(section$concent), indoor_vals$datetime[[i]])

# Get average + SD of each 5-min period for outdoor values
start_idx <- 1
for (i in 2:length(outdoor_vals$concent)-1) {
  time_diff <- unclass(outdoor_vals$datetime[[i+1]]-outdoor_vals$datetime[[i]])
  if (time_diff > 3) {
    section = outdoor_vals[start_idx:i,]
    outdoor_data[nrow(outdoor_data)+1,] = c(mean(section$concent), sd(section$concent), outdoor_vals$datetime[[i]])
    start_idx = i+1
  }
}
section = outdoor_vals[start_idx:i,]
outdoor_data[nrow(outdoor_data)+1,] = c(mean(section$concent), sd(section$concent), outdoor_vals$datetime[[i]])
```

``` {r echo=FALSE}
# Time that the HEPA purifier was started in the classroom

# Create data frame for storing indoor/outdoor particle concentration ratio
indoor_outdoor_ratio <- data.frame("ratio" = double(), "datetime"=double())
for (i in 1:min(length(indoor_data$datetime),length(outdoor_data$datetime))) {
  if (outdoor_data$concent[[i]] > 1) {
    indoor_outdoor_ratio[nrow(indoor_outdoor_ratio)+1,] = c(indoor_data$concent[[i]]/outdoor_data$concent[[i]],indoor_data$datetime[[i]])
  }
}
indoor_outdoor_ratio$datetime <- as.POSIXct(indoor_outdoor_ratio$datetime, tz="America/New_York", origin="1970-01-01")

before_purifier_mean <- mean((indoor_outdoor_ratio[indoor_outdoor_ratio$datetime < purifier_start_time,])$ratio)
after_purifier_mean <- mean((indoor_outdoor_ratio[indoor_outdoor_ratio$datetime > purifier_start_time,])$ratio)

```

```{r}
ggplot(indoor_outdoor_ratio, aes(x=datetime, y=ratio)) +
  geom_line() +
  geom_hline(yintercept=1, linetype="dashed", color="blue") +
  geom_hline(yintercept=before_purifier_mean, linetype="solid", color="red") +
  geom_hline(yintercept=after_purifier_mean, linetype="solid", color="green") +
  geom_vline(xintercept=purifier_start_time, linetype="dashed", color="blue") +
  ylab("indoor/outdoor ratio") +
  xlab("date/time") +
  scale_y_continuous(trans='log10') 
```

```{r}
indoor_data$datetime <- as.POSIXct(indoor_data$datetime, tz="America/New_York", origin="1970-01-01")
outdoor_data$datetime <- as.POSIXct(outdoor_data$datetime, tz="America/New_York", origin="1970-01-01")
ggplot(indoor_data, aes(x=datetime, y=sd, size=1, color='blue')) +
  geom_point(data=outdoor_data, aes(x=datetime, y=sd, size=1, color='red')) 

```

## plot indoor/outdoor averages

``` {r echo=FALSE}
ggplot(indoor_vals, aes(x=datetime, y=concent, size=1, color='blue')) +
  #geom_point() + 
 # geom_point(data=outdoor_vals, aes(x=datetime, y=concent, size=1, color='red')) +
  geom_point(data=indoor_data, aes(x=datetime, y=concent, size=2, color='blue')) 
  #geom_point(data=outdoor_data, aes(x=datetime, y=concent, size=2, color='red'))
```