---
title: "2_28-3_13_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up libraries

```{r}
library(ggplot2)
library(sys)
```

## Load CPC data

```{r}
# Before running this, add a .Renviron file to the project directory and add the line data_filename="<path to the .csv containing the data>"
airdata=read.csv(Sys.getenv("data_filename"),header=T,na.strings="?")
airdata <- na.omit(airdata[airdata$err_num==0,])
airdata$datetime <- as.POSIXct(airdata$timestamp, tz = "America/New_York", format = "%Y-%m-%dT%H:%M:%S", origin="1970-01-01")
purifier_start_time <- as.POSIXct(Sys.getenv("purifier_start_time"), tz = "America/New_York", format = "%Y-%m-%dT%H:%M:%S")

```

## Calculating indoor/outdoor particle ratio
```{r}
indoor_data <- data.frame("concent" = double(), "sd"=double(), "datetime"=double())
outdoor_data <- data.frame("concent" = double(), "sd"=double(), "datetime"=double())

# Filter air data into indoor and outdoor rows
indoor_vals <- airdata[airdata$valve=="a",]
outdoor_vals <- airdata[airdata$valve=="b",]

# Get average + SD of each 5-min period for indoor values
start_idx <- 1
for (i in 2:length(indoor_vals$concent)-1) {
  time_diff <- unclass(indoor_vals$datetime[[i+1]]-indoor_vals$datetime[[i]])
  if (time_diff > 3) {
    section = indoor_vals[start_idx:i,]
    indoor_data[nrow(indoor_data)+1,] = c(mean(section$concent), sd(section$concent), indoor_vals$datetime[[i]])
    start_idx = i+1
  }
}
section = indoor_vals[start_idx:i,]
indoor_data[nrow(indoor_data)+1,] = c(mean(section$concent), sd(section$concent), indoor_vals$datetime[[i]])

# Get average + SD of each 5-min period for outdoor values
start_idx <- 1
for (i in 2:length(outdoor_vals$concent)-1) {
  time_diff <- unclass(outdoor_vals$datetime[[i+1]]-outdoor_vals$datetime[[i]])
  if (time_diff > 3) {
    section = outdoor_vals[start_idx:i,]
    outdoor_data[nrow(outdoor_data)+1,] = c(mean(section$concent), sd(section$concent), outdoor_vals$datetime[[i]])
    start_idx = i+1
  }
}
section = outdoor_vals[start_idx:i,]
outdoor_data[nrow(outdoor_data)+1,] = c(mean(section$concent), sd(section$concent), outdoor_vals$datetime[[i]])
```

## Separate data into before/after HEPA purifier was installed

``` {r}
# Time that the HEPA purifier was started in the classroom

# Create data frame for storing indoor/outdoor particle concentration ratio
indoor_outdoor_ratio <- data.frame("ratio" = double(), "datetime"=double())
for (i in 1:min(length(indoor_data$datetime),length(outdoor_data$datetime))) {
  if (outdoor_data$concent[[i]] > 1 && indoor_data$concent[[i]] > 1) {
    indoor_outdoor_ratio[nrow(indoor_outdoor_ratio)+1,] = c(indoor_data$concent[[i]]/outdoor_data$concent[[i]],indoor_data$datetime[[i]])
  }
}
indoor_outdoor_ratio$datetime <- as.POSIXct(indoor_outdoor_ratio$datetime, tz="America/New_York", origin="1970-01-01")

before_purifier_mean <- mean((indoor_outdoor_ratio[indoor_outdoor_ratio$datetime < purifier_start_time,])$ratio)
after_purifier_mean <- mean((indoor_outdoor_ratio[indoor_outdoor_ratio$datetime > purifier_start_time,])$ratio)

ratio_means = data.frame("mean" = c(before_purifier_mean, after_purifier_mean), "state" = c("before HEPA purifier", "after HEPA purifier"))

```

## Plot mean particle concentration ratio for before/after HEPA purifier installation

```{r fig.width=10}
final_time <- tail(indoor_outdoor_ratio, 1)$datetime
ggplot(indoor_outdoor_ratio, aes(x=datetime, y=ratio)) +
  geom_line(size=1) +
  geom_hline(yintercept=1, linetype="dashed", color="blue") +
  geom_vline(xintercept=purifier_start_time, linetype="dashed", color="blue") +
 # geom_text(data=ratio_means, aes(label = "purifier turned on", x = purifier_start_time, y = 10)) +
  ylab("indoor/outdoor particle ratio") +
  xlab("date/time") + 
  scale_y_log10(limits=c(1e-2,1e1)) +
  geom_hline(yintercept=ratio_means$mean, linetype="solid", color=c("red", "green"))
#      geom_text(data=ratio_means, aes(label = state, x = final_time, y = mean-0.1), hjust=1)

```

## Plot st. dev of concentration levels within each five-minute period

```{r}
indoor_data$datetime <- as.POSIXct(indoor_data$datetime, tz="America/New_York", origin="1970-01-01")
outdoor_data$datetime <- as.POSIXct(outdoor_data$datetime, tz="America/New_York", origin="1970-01-01")
ggplot(indoor_data, aes(x=datetime, y=sd)) + 
  geom_point(color='blue', size=1) +
  geom_point(data=outdoor_data, aes(x=datetime, y=sd), size=1, color='red')

```

```{r}
metdata_clean$datetime <- as.POSIXct(metdata_clean$valid, tz = "America/New_York", format = "%Y-%m-%d %H:%M", origin="1970-01-01")
ggplot(rbind(indoor_data, outdoor_data), aes(x=datetime,y=concent)) + geom_point() +
  geom_point(data=metdata_clean, aes(x=datetime, y=relh))
```
